# Generated by Django 5.1.3 on 2024-12-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_extractedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='classes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='myuser',
            name='conversations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
