# Generated by Django 5.1.3 on 2024-12-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_extractedtext_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.myuser'),
            preserve_default=False,
        ),
    ]
