# Generated by Django 5.1.3 on 2024-12-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_extractedtext_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedtext',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.myuser'),
        ),
    ]
