# Generated by Django 5.1.3 on 2024-11-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='anumber',
            field=models.CharField(max_length=20),
        ),
    ]
