# Generated by Django 5.1.3 on 2024-12-02 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myuser_auth_user_myuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='content',
            field=models.TextField(default='chat'),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
