# Generated by Django 5.1.3 on 2024-12-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_myuser_classes_myuser_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='class_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
