# Generated by Django 5.1.3 on 2024-12-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_extractedtext_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedtext',
            name='user',
        ),
    ]
